### ISSUE TITLE
feature request: skupper as an operator install

### ISSUE THREAD

**Issue by Kampe** [skupperproject/skupper-cli#23]
Is it possible to allow for installation of skupper as an operator?  Is a pain including the binary in edge bootstrapping, for my use case, I'm already managing a handful of operator resources would be ideal if I could just pull down a manifest for the operator and just apply the secret.yaml

**Comment by grs** [comment]
Yes, that is certainly possible. Do you use OLM for managing operators?

**Comment by Kampe** [comment]
We do not currently no - would be interested in moving towards it in the future.  

Ideally we could just grab the yaml from github and apply it at boot, then follow up by laying down our skupper config

**Comment by grs** [comment]
The 0.3.0 release includes an optional site-controller, which behaves much like an operator and allows setup without using the skupper cli. You can deploy the site controller either to watch just the current namespace[1] (i.e. the namespace in which it is deployed) or to watch all namespaces[2].

Once deployed, the site-controller allows a namespace to be initialised simply be creating a configmap named skupper-site within it. That configmap can contain various settings (essentially the same options as can be passed to the CLI in `skupper init`)[3]. 

The site controller will also allow connection tokens to be simply applied as secrets, which will then trigger a connection to the specified skupper site. Note when using tokens generated by the cli, you will likely want/need to change the name of the secret to avoid collisions.

It will also generate tokens. To do so you create an empty secret with label skupper.io/type=connection-token-request, that secret will then have the necessary data inserted into it and can then be exported and transfered to the appropriate site where it can be applied with kubectl apply -f.

[1]  https://raw.githubusercontent.com/skupperproject/skupper/0.3/cmd/site-controller/deploy-watch-current-ns.yaml
[2]  https://raw.githubusercontent.com/skupperproject/skupper/0.3/cmd/site-controller/deploy-watch-all-ns.yaml
[3] https://github.com/skupperproject/skupper/blob/master/cmd/site-controller/README.md

**Comment by Kampe** [comment]
So I just apply the connection token as a secret and the site manager should theoretically see that and deploy the routers?

**Comment by grs** [comment]
You need a configmap called skupper-site first (that is what triggers the setup of the routers with all other necessary setup), and then yes, the connection-token can just be applied and that will configure the routers to connect to the site the token originates from.

**Comment by Kampe** [comment]
So I have this somewhat working, the configmap does lay down the router, however when I apply my secret - nothing happens - none of my skuppered services become available or spawn router pods.

**Comment by grs** [comment]
What do you see for `skupper list-exposed`? From 0.3.0 there are no longer separate pods launched per service, the bridging is done internally in the skupper-router pod.

**Comment by Kampe** [comment]
Unfortunately, I don't have 0.3.0 version of the cli tooling - is that around somewhere - looks like 0.2.0 is the latest and I just get `Error: unknown command "list-exposed" for "skupper`

**Comment by grs** [comment]
Development of the cli has now moved to the skupper repo (not skupper-cli) so releases are there: https://github.com/skupperproject/skupper/releases.

However I think I see the issue you have. The token from the 0.2.0 client has the name 'skupper' and by having this applied before the site controller is created, it prevents the site controller writing the expected secret for internal communication (hence the ssl errors in the logs you are seeing).

So, for now you need to delete the 'skupper' secret *and* 'skupper-site' configmap, then recreate the configmap first. You then need to edit the token to change the name from 'skupper' to something else before you apply it. That should then hopefully work.

**Comment by Kampe** [comment]
Okay excellent, in reference to the secret that needs to be renamed and applied, should I expect to put a specific annotation on said secret for skupper to know this is the renamed secret to utilize as a connection token?

**Comment by Kampe** [comment]
Aha, figured that out - can I have this secret exist before the site-controller stands up? 

secret does need
```
  labels:
    skupper.io/type: connection-token
```

**Comment by grs** [comment]
The token should already have the label on it when generated. Providing the name doesn't clash, then yes the secret can be applied before the site controller is deployed.

(The problem is that at present the site-controller assumes that the secret called 'skupper' is previously generated certs for the local site, but the default token name from 0.2.0 will also be 'skupper')

**Comment by grs** [comment]
Great, glad it is working! (Will try to ensure we handle the clash better in future).

**Comment by Kampe** [comment]
Well - may have spoke a little prematurely!  I do have my services skuppered into my other cluster - however my connections all just fail when attempting to utilize the services.  

output from `skupper list-exposed`
```
Services exposed through Skupper:
    global-service (tcp port 8080)
    global-api (tcp port 5443)****
```

**Comment by grs** [comment]
```[C5] Connection from 127.0.0.1:60830 (to 0.0.0.0:45671) failed: amqp:resource-limit-exceeded local-idle-timeout expired```

That suggests that the router connection from the edge site was lost, due to the edge site router not sending a heartbeat. That in turn would suggest either some connectivity issue or a scheduling/cpu issue with the edge router. What do the edge router logs look like?

Also if you run `qdstat -n` and `qdstat -c` and `qdstat -l` against the router pod in each site that will give some useful information. (We have an issue open to simplify the collection of all this, so apologies for the many steps at this stage!).

**Comment by Kampe** [comment]
Ah didn't notice I'm seeing these in edge bridge server - may be useful

```
│ 2020-08-21T19:17:47.879Z bridge-server error Cannot find correlation id for failed delivery                                                                                                                                                                                                                                                   
│ Could not deliver request                                                                                                                                                                                                                                                                                                                     
│ (node:1) UnhandledPromiseRejectionWarning: ReferenceError: site is not defined                                                                                                                                                                                                                                                                
│     at /opt/app-root/lib/bridges.js:181:120                                                                                                                                                                                                                                                                                                   
│     at process._tickCallback (internal/process/next_tick.js:68:7)                                                                                                                                                                                                                                                                             
│ (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)                                                                                          
│ (node:1) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.                                                                                                                                      
│ Could not deliver request                                                                                                                                                                                                                                                                                                                     
│ (node:1) UnhandledPromiseRejectionWarning: ReferenceError: site is not defined                                                                                                                                                                                                                                                                
│     at /opt/app-root/lib/bridges.js:181:120                                                                                                                                                                                                                                                                                                   
│     at process._tickCallback (internal/process/next_tick.js:68:7)                                                                                                                                                                                                                                                                             
│ (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)                                                                                          
│ 2020-08-21T19:17:54.651Z bridge-server info outgoing request global-api:5443 (global-api/***/***)                                                                                                                                                                                                                      
│ 2020-08-21T19:17:54.651Z bridge-server info client sending message: GET global-api/***/***                                                                                                                                                                                                                                
│ 2020-08-21T19:18:40.460Z bridge-server error Cannot find correlation id for failed delivery                                                                                                                                                                                                                                                   
│ Could not deliver request                                                                                                                                                                                                                                                                                                                     
│ (node:1) UnhandledPromiseRejectionWarning: ReferenceError: site is not defined                                                                                                                                                                                                                                                                
│     at /opt/app-root/lib/bridges.js:181:120                                                                                                                                                                                                                                                                                                   
│     at process._tickCallback (internal/process/next_tick.js:68:7)                                                                                                                                                                                                                                                                             
│ (node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
```

**Comment by grs** [comment]
Thanks! What image version is the bridge-server container?

**Comment by Kampe** [comment]
Both clusters are using `Image: quay.io/skupper/bridge-server:0.3`
